### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by kytrinyx**
Clarify the purpose of the repository and explain the project vs product distinction (and labels).

### CODE REVIEW

**Comment by Insti** [comment]
This might be a separate project discussion but `project` and `product` are hard words to visually distinguish from each other.

**Comment by kytrinyx** [comment]
That's true. How about user-facing instead of product?

**Comment by kytrinyx** [comment]
Or even ux... everything that is user facing is user experience...

**Comment by Insti** [comment]
Would product include things that are not specifically user visible?
eg. Refactoring the website code?

Maybe `organisation` instead of `project`?

**Comment by kytrinyx** [comment]
I wouldn't include refactoring in the user-specific stuff. I suppose organization could work. It leans a little bit towards feeling like "logistics", whereas I mean anything that is about the open source project itself (processes, documentation, tools, automation, community stuff, ...) but I think it works.

**Comment by kytrinyx** [comment]
I went with "open source" instead of "project".

**Pull request merged**
